package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/mfahlandt/lwcn/internal/cncf"
	"github.com/mfahlandt/lwcn/internal/config"
	"github.com/mfahlandt/lwcn/internal/models"
	"gopkg.in/yaml.v3"
)

func main() {
	outputPath := flag.String("output", "config/repositories.yaml", "Path to write the merged repositories config")
	additionalPath := flag.String("additional", "config/additional-repos.yaml", "Path to additional repositories config")
	dryRun := flag.Bool("dry-run", false, "Print the result without writing to file")
	flag.Parse()

	// Step 1: Fetch CNCF projects from Landscape API
	cncfRepos, err := cncf.FetchCNCFProjects()
	if err != nil {
		log.Fatalf("Failed to fetch CNCF projects: %v", err)
	}

	log.Printf("Fetched %d repositories from CNCF Landscape", len(cncfRepos))

	// Step 2: Load additional repositories (if file exists)
	var additionalRepos []models.Repository
	if _, err := os.Stat(*additionalPath); err == nil {
		additionalCfg, err := config.LoadAdditionalRepositories(*additionalPath)
		if err != nil {
			log.Fatalf("Failed to load additional repositories from %s: %v", *additionalPath, err)
		}
		additionalRepos = additionalCfg.AdditionalRepositories
		log.Printf("Loaded %d additional repositories from %s", len(additionalRepos), *additionalPath)
	} else {
		log.Printf("No additional repositories file found at %s, skipping", *additionalPath)
	}

	// Step 3: Merge - CNCF projects take priority, additional repos fill gaps
	merged := mergeRepositories(cncfRepos, additionalRepos)

	log.Printf("Merged result: %d total repositories", len(merged))

	// Step 4: Print summary
	printSummary(merged)

	// Step 5: Write output
	repoCfg := models.RepositoryConfig{
		Repositories: merged,
	}

	data, err := marshalRepositoriesYAML(repoCfg)
	if err != nil {
		log.Fatalf("Failed to marshal config: %v", err)
	}

	if *dryRun {
		fmt.Println("--- DRY RUN: would write the following to", *outputPath, "---")
		fmt.Println(string(data))
		return
	}

	if err := os.WriteFile(*outputPath, data, 0644); err != nil {
		log.Fatalf("Failed to write output: %v", err)
	}

	log.Printf("Successfully wrote %d repositories to %s", len(merged), *outputPath)
}

// mergeRepositories merges CNCF repos with additional repos.
// CNCF repos take priority. Additional repos are only added if not already present.
func mergeRepositories(cncfRepos, additionalRepos []models.Repository) []models.Repository {
	seen := make(map[string]bool)
	var result []models.Repository

	// Add all CNCF repos first
	for _, r := range cncfRepos {
		key := strings.ToLower(r.Owner + "/" + r.Repo)
		if seen[key] {
			continue
		}
		seen[key] = true
		result = append(result, r)
	}

	// Add additional repos that are not already in the CNCF list
	added := 0
	for _, r := range additionalRepos {
		key := strings.ToLower(r.Owner + "/" + r.Repo)
		if seen[key] {
			continue
		}
		seen[key] = true
		result = append(result, r)
		added++
	}

	log.Printf("Added %d additional repositories not found in CNCF landscape", added)

	// Sort: graduated first, then incubating, then sandbox, then additional (no status)
	sort.Slice(result, func(i, j int) bool {
		oi := statusOrder(result[i].CNCFStatus)
		oj := statusOrder(result[j].CNCFStatus)
		if oi != oj {
			return oi < oj
		}
		// Within same status, sort by name
		return strings.ToLower(result[i].Name) < strings.ToLower(result[j].Name)
	})

	return result
}

func statusOrder(status string) int {
	switch strings.ToLower(status) {
	case "graduated":
		return 0
	case "incubating":
		return 1
	case "sandbox":
		return 2
	default:
		return 3
	}
}

func printSummary(repos []models.Repository) {
	counts := make(map[string]int)
	for _, r := range repos {
		status := r.CNCFStatus
		if status == "" {
			status = "additional"
		}
		counts[status]++
	}

	log.Println("Repository summary:")
	for _, status := range []string{"graduated", "incubating", "sandbox", "additional"} {
		if c, ok := counts[status]; ok {
			log.Printf("  %-12s: %d repos", status, c)
		}
	}
}

// marshalRepositoriesYAML produces a nicely formatted YAML output with section comments
func marshalRepositoriesYAML(cfg models.RepositoryConfig) ([]byte, error) {
	var buf strings.Builder

	buf.WriteString("# Auto-generated by sync-cncf-projects\n")
	buf.WriteString("# Do not edit manually - run 'make sync-repos' to update\n")
	buf.WriteString("#\n")
	buf.WriteString("# Sources:\n")
	buf.WriteString("#   - CNCF Landscape API (https://landscape.cncf.io)\n")
	buf.WriteString("#   - config/additional-repos.yaml\n")
	buf.WriteString("\n")

	currentStatus := ""
	for _, r := range cfg.Repositories {
		status := r.CNCFStatus
		if status == "" {
			status = "additional"
		}

		if status != currentStatus {
			currentStatus = status
			header := strings.ToUpper(currentStatus) + " PROJECTS"
			if currentStatus == "additional" {
				header = "ADDITIONAL PROJECTS (non-CNCF)"
			}
			buf.WriteString(fmt.Sprintf("\n  # ============================================\n"))
			buf.WriteString(fmt.Sprintf("  # %s\n", header))
			buf.WriteString(fmt.Sprintf("  # ============================================\n"))
		}
	}

	// For the actual YAML, use the standard marshaler but we want our comments
	// So let's build it manually with proper structure
	buf.Reset()

	buf.WriteString("# Auto-generated by sync-cncf-projects\n")
	buf.WriteString("# Do not edit manually - run 'make sync-repos' to update\n")
	buf.WriteString("#\n")
	buf.WriteString("# Sources:\n")
	buf.WriteString("#   - CNCF Landscape API (https://landscape.cncf.io)\n")
	buf.WriteString("#   - config/additional-repos.yaml\n")
	buf.WriteString("\nrepositories:\n")

	currentStatus = ""
	for _, r := range cfg.Repositories {
		status := r.CNCFStatus
		if status == "" {
			status = "additional"
		}

		if status != currentStatus {
			currentStatus = status
			header := strings.ToUpper(currentStatus) + " PROJECTS"
			if currentStatus == "additional" {
				header = "ADDITIONAL PROJECTS (non-CNCF)"
			}
			buf.WriteString(fmt.Sprintf("\n  # ============================================\n"))
			buf.WriteString(fmt.Sprintf("  # %s\n", header))
			buf.WriteString(fmt.Sprintf("  # ============================================\n"))
		}

		// Marshal individual repo entry
		entry := map[string]interface{}{
			"owner":    r.Owner,
			"repo":     r.Repo,
			"name":     r.Name,
			"category": r.Category,
		}
		if r.CNCFStatus != "" {
			entry["cncf_status"] = r.CNCFStatus
		}

		entryData, err := yaml.Marshal(entry)
		if err != nil {
			return nil, err
		}

		// Write as list item
		lines := strings.Split(strings.TrimSpace(string(entryData)), "\n")
		for i, line := range lines {
			if i == 0 {
				buf.WriteString("  - " + line + "\n")
			} else {
				buf.WriteString("    " + line + "\n")
			}
		}
	}

	return []byte(buf.String()), nil
}
